

import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthGuard from "./auth-guard";
import SidebarVisibility from "./SidebarVisibility";
import ChatbotVisibility from "./ChatbotVisibility";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ChatbotVisibility />
        <div style={{ display: 'flex', minHeight: '100vh' }}>
          <SidebarVisibility />
          <div style={{ flex: 1 }}>
            <AuthGuard>{children}</AuthGuard>
          </div>
        </div>
      </body>
    </html>
  );
}
